# -*- coding: utf-8 -*-
"""textToSpeech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JIxO6LVrk0I3GYJZttUlK2PiAHMl4xMf
"""

# install bark as well as pytorch nightly to get blazing fast flash-attention
!pip install git+https://github.com/suno-ai/bark.git && \
  pip uninstall -y torch torchvision torchaudio && \
  pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118

from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio

preload_models()

def convertToSpeech(text_prompt):
    audio_array = generate_audio(text_prompt)
    Audio(audio_array, rate=SAMPLE_RATE)